### ISSUE TITLE
d3不显示问题

### ISSUE THREAD

**Issue by 944916121** [gywgithub/vue-d3-examples#1]
源码移到自己项目中，报错
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.invokeGetter (<anonymous>:1:142)
    at VueComponent.mounted (http://localhost/app.7b5921888298c407bb52.hot-update.js:292:21)
    at invokeWithErrorHandling (http://localhost/app.js:132484:57)
    at callHook (http://localhost/app.js:134838:7)
    at Object.insert (http://localhost/app.js:133767:7)
    at invokeInsertHook (http://localhost/app.js:136961:28)
    at VueComponent.patch [as __patch__] (http://localhost/app.js:137180:5)
    at VueComponent.Vue._update (http://localhost/app.js:134567:19)
    at VueComponent.updateComponent (http://localhost/app.js:134685:10)
    at Watcher.get (http://localhost/app.js:135098:25)

**Comment by gywgithub** [comment]
vue-d3-examples 项目在本地运行正常吗？如果本地可以正常运行，按需引入例子代码到项目应该就可以了，注意模块引入问题

**Comment by 944916121** [comment]
> vue-d3-examples 项目在本地运行正常吗？如果本地可以正常运行，按需引入例子代码到项目应该就可以了，注意模块引入问题

 vue-d3-examples 项目本地运行正常的，Zoomable.vue这个文件移到自己的项目中就有问题，d3也安装了，不知道问题在哪，纠结了好久

**Comment by gywgithub** [comment]
@944916121  你这样操作一下，你单独用vue-cli3+ 创建一个新的 vue 项目，然后在这个项目里添加 vue-d3-examples 中的例子，这样没有项目功能代码干扰，你的情况应该是安装或引用的时候哪里没弄好；还有，查看一下 vue-d3-examples 和你项目中 vue ，d3 版本是否一致

**Comment by 944916121** [comment]
> @944916121 你这样操作一下，你单独用vue-cli3+ 创建一个新的 vue 项目，然后在这个项目里添加 vue-d3-examples 中的例子，这样没有项目功能代码干扰，你的情况应该是安装或引用的时候哪里没弄好；还有，查看一下 vue-d3-examples 和你项目中 vue ，d3 版本是否一致

d3版本一定要一致吗

**Comment by gywgithub** [comment]
版本一致能保证你能实现 vue-d3-examples 中的例子，不同的版本函数实现会有改变，可能会遇到额外问题

**Comment by 944916121** [comment]
您好，之前的图表不显示问题是我这边用错选择器导致的。现在图表显示了，但是图表中的设备分支都挤在一起，我想把它们平均分散开来，该怎么改呢

&nbsp;


冯婷婷

944916121@qq.com
未来网络，引领未来


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YW"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 中午11:49
收件人:&nbsp;"gywgithub/vue-d3-examples"<vue-d3-examples@noreply.github.com&gt;;
抄送:&nbsp;"冯婷婷"<944916121@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [gywgithub/vue-d3-examples] d3不显示问题 (#1)




@944916121  你这样操作一下，你单独用vue-cli3+ 创建一个新的 vue 项目，然后在这个项目里添加 vue-d3-examples 中的例子，这样没有项目功能代码干扰，你的情况应该是安装或引用的时候哪里没弄好；还有，查看一下 vue-d3-examples 和你项目中 vue ，d3 版本是否一致

**Comment by gywgithub** [comment]
@944916121   你没有表达清楚你遇到的问题，也没有效果图，不清楚你的问题是怎么回事，可能你对D3还不了解，建议你先看下[D3官网](https://d3js.org)的基础知识和介绍，再看你项目中的问题可能会帮助你定位问题原因。

**Comment by 944916121** [comment]
我想实现图一效果图，分支是以Myriel为中心点围绕四周，而不是挤在一起，目前我是通过设置distance=100，但是我想link线条变长，当设置distance的值大于200的时候，就会展现成图二的效果图
图一





图二


冯婷婷

944916121@qq.com





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YW"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 下午3:31
收件人:&nbsp;"gywgithub/vue-d3-examples"<vue-d3-examples@noreply.github.com&gt;;
抄送:&nbsp;"冯婷婷"<944916121@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [gywgithub/vue-d3-examples] d3不显示问题 (#1)





 
@944916121   你没有表达清楚你遇到的问题，也没有效果图，不清楚你的问题是怎么回事，可能你对D3还不了解，建议你先看下D3官网的基础知识和介绍，再看你项目中的问题可能会帮助你定位问题原因。

**Comment by gywgithub** [comment]
图片看不到，你打开这个链接 [ https://github.com/gywgithub/vue-d3-examples/issues/1 ]( https://github.com/gywgithub/vue-d3-examples/issues/1 ) 看下

**Comment by gywgithub** [comment]
@944916121  你可以尝试修改 `d3.forceManyBody().strength()` 函数中的值，这个是控制力的大小的，也许可以解决你的疑问

**Comment by 944916121** [comment]
你好：
&nbsp; &nbsp;我是之前咨询过d3插件不显示问题的人
现在我在工作中又遇到问题了，现在想咨询Vue集成activity工作流的开发，还请大神多多指教



&nbsp;冯婷婷
Tel:18795880051

QQ:944916121
时间：2020年11月25日

**Comment by gywgithub** [comment]
可以把遇到的问题具体描述一下回复到到这里，包含报错信息等等，如果文字不好描述，可以加我QQ，你可以屏幕共享，或者请求远程协助
QQ：1119536080

**Comment by 944916121** [comment]
已加你qq

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gywgithub/vue-d3-examples"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 上午8:26
收件人:&nbsp;"gywgithub/vue-d3-examples"<vue-d3-examples@noreply.github.com&gt;;
抄送:&nbsp;"冯婷婷"<944916121@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [gywgithub/vue-d3-examples] d3不显示问题 (#1)





 
可以把遇到的问题具体描述一下回复到到这里，包含报错信息等等，如果文字不好描述，可以加我QQ，你可以屏幕共享，或者请求远程协助
 QQ：1119536080
