### ISSUE TITLE
force-director-graph在节点周围怎么绘制其他图标呢

### ISSUE THREAD

**Issue by jim888666** [gywgithub/vue-d3-examples#4]
鼠标移入节点周围显示 锁 扩展 删除 图标，怎么绘制呢？

**Comment by gywgithub** [comment]
可以通过设置节点的 `mouseover` 事件函数满足业务具体操作
~~~
.on('mouseover', function () {
  // do something
})
~~~
eg.
https://github.com/gywgithub/vue-d3-examples/blob/dev/src/components/CompleteHistogramIII.vue#L57

https://github.com/gywgithub/vue-d3-examples/blob/dev/src/components/ForceBasedLabelPlacementI.vue#L95

**Comment by jim888666** [comment]
好的 谢谢
